# Generated by Django 3.0 on 2024-05-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240504_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
