# Generated by Django 3.0 on 2024-05-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240504_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
